jobs:
  - name: test-1
    runtime:
      container: true
      options:
          imageName: drydock/microbase
          imageTag: v6.1.3
          pull: true
    steps:
      TASK:
        script:
          - /opt/az/bin/python3 -c "print ('hello');"
