jobs:
  - name: test-1
    type: runSh
    runtime:
      container: true
      options:
          imageName: drydock/microbase
          imageTag: v6.1.3
          pull: true
    steps:
      - TASK:
          script:
            - az --version || true
            - az account list || true
            - /opt/az/bin/python3 -c "print ('hello');"
